sudo: required

services: docker

bofore_install:
  - docker-compose up --build -d

script:
  - docker-compose exec --env "RAILS_ENV=test" we brails db:create
  - docker-compose exec --env "RAILS_ENV=test" we brails db:migrate
  - docker-compose exec --env "RAILS_ENV=test" we brails test 